add SHA224 module
dfinity/vessel-package-set pull request #20
Opened 2021-05-21 15:49 UTC by flyq

2021-05-21 17:59 UTC, kritzcreek requested changes
Just one small nit, but otherwise looks great!

2021-05-21 17:59 UTC, kritzcreek commented on index/sha224.dhall
> +, owners = [ "Enzo Haussecker", "flyq" ]
This array should contain Github user names (I'll use these to ping people in case their packages fall behind newer compiler versions)

2021-05-22 00:36 UTC, flyq commented on index/sha224.dhall
> +, owners = [ "Enzo Haussecker", "flyq" ]
I see, I modified it

2021-05-22 08:10 UTC, kritzcreek approved these changes

2021-05-22 08:11 UTC, merged

2021-05-22 08:12 UTC, kritzcreek commented
Available starting with `mo-0.6.1-20210522`