Sequence package.
dfinity/vessel-package-set pull request #29
Opened 2021-07-08 22:59 UTC by matthewhammer

Persistent sequence representation and algorithms.

Already used by CanCan and other example Dapps, but not yet officially listed here.

2021-07-08 23:25 UTC, chenyan-dfinity commented
You also need an entry here: https://github.com/dfinity/vessel-package-set/blob/main/src/packages.dhall

2021-07-09 16:24 UTC, chenyan-dfinity commented on index/sequence.dhall
> +, homepage = "http://matthewhammer.org/motoko-sequence/"
```suggestion
, homepage = Some "http://matthewhammer.org/motoko-sequence/"
```

2021-07-09 17:03 UTC, matthewhammer commented
Thanks for the help @chenyan-dfinity  -- PTAL.

2021-07-09 17:04 UTC, chenyan-dfinity approved these changes

2021-07-12 07:52 UTC, kritzcreek requested changes

2021-07-12 07:52 UTC, kritzcreek commented on index/sequence.dhall
> +, version = "2b7b429224a87c72ac002482669b514754e07988"
Please tag a version and include that instead of a commit hash. `base` is the outlier here because we don't have a good versioning strategy for that yet.

Also see https://github.com/dfinity/vessel-package-set/blob/main/CONTRIBUTING.md#general

2021-07-12 07:52 UTC, kritzcreek commented on index/sequence.dhall
> +, dependencies = [ "base", "crud" ]
It seems weird for a datastructure library to depend on the `crud` package, is that a real dependency, or only used in the tests for `sequence`?

2021-07-12 21:02 UTC, matthewhammer commented on index/sequence.dhall
> +, dependencies = [ "base", "crud" ]
Yeah, I agree.

Yep, the example service "BigSearch" (probably misnamed) uses it.  It'd be nice to separate them, but it's not clear how to do that without more repos, which I don't want or need.  Any suggestions?

This brings up a common pattern that I find, and that I've noted before (maybe even in my original review of vessel?): It's often desirable to have two dependency sets, one for building test/example services with `dfx`, and a (smaller sub) set for building the core library, if applicable.  Many of my packages have followed this pattern, and it seems similar to the notion of test builds and test binaries in Rust, which can have their own crate dependencies.

2021-07-12 21:16 UTC, chenyan-dfinity commented on index/sequence.dhall
> +, dependencies = [ "base", "crud" ]
Maybe we need a `src` field, so that we can have multiple libraries within one repo.

2021-07-12 23:50 UTC, matthewhammer commented on index/sequence.dhall
> +, dependencies = [ "base", "crud" ]
IIUC, we need to have a way to have multiple vessel packages in one repo, and now, we assume each vessel package is one distinct repo (identified by a github repo and version, but no `src` path within it).

Your suggestion is to identify a package by a repo, version (or hash) and a source path?

Seems right to me.

But we'd also need a convention for naming and organizing the `vessel.dhall` and `package-set.dhall` files when they may reappear in a repo (they are no longer "singleton instances" within a repo).  Would they go into the root of that `src` path and keep the same names as now?

2021-07-13 07:26 UTC, kritzcreek commented on index/sequence.dhall
> +, dependencies = [ "base", "crud" ]
> Yep, the example service "BigSearch" (probably misnamed) uses it. It'd be nice to separate them, but it's not clear how to do that without more repos, which I don't want or need. Any suggestions?

The dependencies declared in the package-set are purely what's relevant for someone using your library. So `crud` shouldn't be in this list, as they can only import the files in your `src/` directory.

`vessel` doesn't care if there's a `vessel.dhall` file in your repository. It only cares about a `src/` directory with Motoko source files, so feel free to declare test/example dependencies in your own repository.

> It's often desirable to have two dependency sets, one for building test/example services with dfx, and a (smaller sub) set for building the core library, if applicable. 

Here's one way of handling a projects test vs lib dependencies: https://github.com/kritzcreek/motoko-library-template/tree/main/test. Check out the `vessel.dhall` and `package-set.dhall` files in there.

2021-07-13 17:55 UTC, matthewhammer commented on index/sequence.dhall
> +, dependencies = [ "base", "crud" ]
> The dependencies declared in the package-set are purely what's relevant for someone using your library.

Well, that is not so for `dfx` users, including the use case of `dfx` in the sequence package repo.

When `vessel` is used by`dfx`, it presents another use case that I also care about here.  Are you considering that as well?

> Here's one way of handling a projects test vs lib dependencies...

There is no use of `dfx` there, and that's my concern.  I don't see how it applies.

2021-07-13 22:08 UTC, matthewhammer commented on index/sequence.dhall
> +, dependencies = [ "base", "crud" ]
Here's my [latest compromise attempt](https://github.com/matthewhammer/motoko-sequence/pull/28), which permits me to do what we both agree is preferable: remove `crud` from the dependency list of `sequence`, the vessel package.  I've now done that.

WDYT?

2021-07-14 07:32 UTC, kritzcreek approved these changes

2021-07-14 07:32 UTC, merged

2021-07-14 07:34 UTC, kritzcreek commented on index/sequence.dhall
> +, dependencies = [ "base", "crud" ]
PR looks good to me now. Dealing with `dfx` is definitely tricky... I am tracking ideas around multiple targets for vessel packages here: https://github.com/dfinity/vessel/issues/26

It's possible the thing you'd like to see would only happen as part of a `vessel build` where we teach `vessel` how to build canisters, and not just be a dependency manager,

2021-07-14 07:35 UTC, kritzcreek commented
Available starting with `mo-0.6.5-20210714`

2021-07-14 19:47 UTC, matthewhammer commented on index/sequence.dhall
> +, dependencies = [ "base", "crud" ]
> the thing you'd like to see would only happen as part of a vessel build where we teach vessel how to build canisters, and not just be a dependency manager

Yeah, that sounds right to me.  There's a "gap" where I want vessel to build canisters, and come closer to subsuming the structure of the build steps of `dfx`, at least for building Motoko canisters.